package sc;
/*
 * Main.java
 *
 * Created on April 19, 2007, 11:27 AM
 */

import javax.swing.*;

import com.linuxnet.jpcsc.*;

public class Main extends javax.swing.JFrame {
    
    MyKad mykad = new MyKad();
    
    /** Creates new form Main */
    public Main() {        
        initComponents();    
        
        mykad.start();
        mykad.useJPN();        
        
        mykad.readData();              
        
        jLblNoKP.setText(mykad.ic);
        jLblNama.setText(mykad.name);
        jLblJantina.setText(mykad.gender);   
        jLblNoKPLama.setText(mykad.oldIc);
        jLblTarikhLahir.setText(mykad.dob);
        jLblTempatLahir.setText(mykad.birthPlace);
        jLblWarganegara.setText(mykad.citizenship);
        jLblKaum.setText(mykad.race);
        jLblAgama.setText(mykad.religion);
        jLblAlamat1.setText(mykad.address1);
        jLblAlamat2.setText(mykad.address2);
        jLblAlamat3.setText(mykad.address3);
        jLblPoskod.setText(mykad.poscode);
        jLblBandar.setText(mykad.city);
        jLblNegeri.setText(mykad.state);
        
        jLblPic.setIcon(mykad.getPic());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLblNama = new javax.swing.JLabel();
        jLblNoKP = new javax.swing.JLabel();
        jLblNoKPLama = new javax.swing.JLabel();
        jLblJantina = new javax.swing.JLabel();
        jLblTarikhLahir = new javax.swing.JLabel();
        jLblNegeri = new javax.swing.JLabel();
        jLblPoskod = new javax.swing.JLabel();
        jLblBandar = new javax.swing.JLabel();
        jLblAlamat3 = new javax.swing.JLabel();
        jLblAlamat2 = new javax.swing.JLabel();
        jLblTempatLahir = new javax.swing.JLabel();
        jLblWarganegara = new javax.swing.JLabel();
        jLblKaum = new javax.swing.JLabel();
        jLblAgama = new javax.swing.JLabel();
        jLblAlamat1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLblPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyKad");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 11));
        jLabel1.setText("No KP:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 11));
        jLabel4.setText("No KP Lama:");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 11));
        jLabel10.setText("Nama:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 11));
        jLabel2.setText("Jantina:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 11));
        jLabel3.setText("Tarikh Lahir:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 11));
        jLabel5.setText("Tempat Lahir:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 11));
        jLabel6.setText("Warganegara:");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 11));
        jLabel7.setText("Kaum:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 11));
        jLabel8.setText("Agama:");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 11));
        jLabel9.setText("Alamat:");

        jLblNama.setFont(new java.awt.Font("Dialog", 0, 11));
        jLblNama.setText("<html><u>nil");

        jLblNoKP.setFont(new java.awt.Font("Dialog", 0, 11));
        jLblNoKP.setText("<html><u>nil");

        jLblNoKPLama.setFont(new java.awt.Font("Dialog", 0, 11));
        jLblNoKPLama.setText("<html><u>nil");

        jLblJantina.setFont(new java.awt.Font("Dialog", 0, 11));
        jLblJantina.setText("<html><u>nil");

        jLblTarikhLahir.setFont(new java.awt.Font("Dialog", 0, 11));
        jLblTarikhLahir.setText("<html><u>nil");

        jLblNegeri.setFont(new java.awt.Font("Dialog", 0, 11));
        jLblNegeri.setText("<html><u>nil");

        jLblPoskod.setFont(new java.awt.Font("Dialog", 0, 11));
        jLblPoskod.setText("<html><u>nil");

        jLblBandar.setFont(new java.awt.Font("Dialog", 0, 11));
        jLblBandar.setText("<html><u>nil");

        jLblAlamat3.setFont(new java.awt.Font("Dialog", 0, 11));
        jLblAlamat3.setText("<html><u>nil");

        jLblAlamat2.setFont(new java.awt.Font("Dialog", 0, 11));
        jLblAlamat2.setText("<html><u>nil");

        jLblTempatLahir.setFont(new java.awt.Font("Dialog", 0, 11));
        jLblTempatLahir.setText("<html><u>nil");

        jLblWarganegara.setFont(new java.awt.Font("Dialog", 0, 11));
        jLblWarganegara.setText("<html><u>nil");

        jLblKaum.setFont(new java.awt.Font("Dialog", 0, 11));
        jLblKaum.setText("<html><u>nil");

        jLblAgama.setFont(new java.awt.Font("Dialog", 0, 11));
        jLblAgama.setText("<html><u>nil");

        jLblAlamat1.setFont(new java.awt.Font("Dialog", 0, 11));
        jLblAlamat1.setText("<html><u>nil");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel10)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel6)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel7)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel8)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel9))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLblNegeri, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(jLblTarikhLahir, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jLblPoskod, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLblBandar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLblNoKP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(jLblNoKPLama, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(jLblNama, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(jLblJantina, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(jLblTempatLahir, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(jLblWarganegara, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(jLblKaum, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(jLblAgama, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(jLblAlamat1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(jLblAlamat2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(jLblAlamat3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLblNoKP))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jLblNoKPLama))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(jLblNama))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLblJantina))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jLblTarikhLahir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jLblTempatLahir))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(jLblWarganegara))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jLblKaum))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(jLblAgama))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(jLblAlamat1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLblAlamat2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLblAlamat3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLblBandar)
                    .add(jLblPoskod))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLblNegeri)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Picture"));
        jLblPic.setFont(new java.awt.Font("Dialog", 0, 11));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLblPic, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jLblPic, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        mykad.stop();        
    }//GEN-LAST:event_formWindowClosing
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main main = new Main();
                main.setLocationRelativeTo(null);
                main.setVisible(true);  
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblAgama;
    private javax.swing.JLabel jLblAlamat1;
    private javax.swing.JLabel jLblAlamat2;
    private javax.swing.JLabel jLblAlamat3;
    private javax.swing.JLabel jLblBandar;
    private javax.swing.JLabel jLblJantina;
    private javax.swing.JLabel jLblKaum;
    private javax.swing.JLabel jLblNama;
    private javax.swing.JLabel jLblNegeri;
    private javax.swing.JLabel jLblNoKP;
    private javax.swing.JLabel jLblNoKPLama;
    private javax.swing.JLabel jLblPic;
    private javax.swing.JLabel jLblPoskod;
    private javax.swing.JLabel jLblTarikhLahir;
    private javax.swing.JLabel jLblTempatLahir;
    private javax.swing.JLabel jLblWarganegara;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
